name: Linux build
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2

      - name: Install linux dependencies
        run: sudo apt-get update && sudo apt-get install -y libudev-dev pkg-config protobuf-compiler libdrm-dev

      - run: cargo test

      - run: cargo build --release
